CREATE TABLE customer
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    iban          CHAR(18)     NOT NULL,
    full_name     VARCHAR(200) NOT NULL,
    date_of_birth DATE         NOT NULL,
    country_code  CHAR(2)      NOT NULL,
    street        VARCHAR(200) NOT NULL,
    house_number  VARCHAR(50)  NOT NULL,
    postal_code   VARCHAR(32)  NOT NULL,

    CONSTRAINT uq_customer_username UNIQUE (username),
    CONSTRAINT uq_customer_iban UNIQUE (iban)
);
