CREATE TABLE account
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT         NOT NULL,
    iban         CHAR(18)       NOT NULL,
    account_type VARCHAR(20)    NOT NULL DEFAULT 'PRIVATE',
    balance      DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    currency     CHAR(3)        NOT NULL DEFAULT 'EUR',

    CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT uq_account_customer UNIQUE (customer_id),
    CONSTRAINT uq_account_iban UNIQUE (iban)
);

INSERT INTO account (customer_id, iban)
SELECT id, iban
FROM customer;

ALTER TABLE customer DROP CONSTRAINT uq_customer_iban;
ALTER TABLE customer DROP COLUMN iban;
